openapi: "3.0.0"
info:
  version: 1.0.0
  title: String
servers:
  - url: http://localhost:8080
paths:
  /generate/license-plate-number:
    get:
      summary: Generates license plate number
      operationId: generateLicensePlateNumber
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
  /utilities:
    get:
      summary: String Manipulation Utilities
      operationId: utilities
      tags:
        - utilities
      parameters:
        - name: action
          in: query
          description: the action that should be executed
          required: true
          schema:
            type: string
      responses:
        '200':
          description: String manipulation utilities
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    Response:
      required:
        - text
      properties:
        text:
          type: string